Plant/urls.py
from django.conf.urls import url
from . import views

app_name = 'Plant'

urlpatterns = [url(r'^send/$', views.getdata, name='getdata'),
               url(r'^makeUser/$', views.makeUser, name='makeUser'),
               url(r'^userProfile/$', views.userprofile, name='userProfile'),
               url(r'home/$', views.home, name='home'),
               url(r'^home/(?P<name>\w+)/$', views.home, name='home'),
               url(r'^addplant/(?P<name>\w+)/$', views.addplant, name='addplant'),
               url(r'^userPlants/(?P<name>\w+)/(?P<plant_name>\w+)/$', views.userPlants, name='userPlants'),
               url(r'^editUser/(?P<name>\w+)/$', views.editUser, name='editUser'),
               url(r'^signup/$', views.signup, name='signup'),
               url(r'^login/$', views.login, name='login'),
               url(r'^logout/$', views.logout, name='logout'),
               ]

Project_16/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

app_name = 'Plant'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^Plant/', include('Plant.urls')),
    url(r'^$', views.home, name='home'),
]

Plant/models.py
from django.db import models
from datetime import datetime

'''This is a user model. It stores detail of user.'''


class User(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(max_length=255, blank=True)
    password = models.CharField(max_length=200)

    def __str__(self):
        return str(self.name)

'''This is a Plant model. It stores details of a plant.'''


class Plants(models.Model):
    uid = models.ForeignKey(User, on_delete=models.CASCADE)
    plant_name = models.CharField(max_length=100, blank=True)
    lat = models.FloatField(default=0.0)
    lon = models.FloatField(default=0.0)
    dt = models.DateTimeField(default=datetime.now(),)

    def __str__(self):
        return str(self.plant_name)

'''This is a temperature model. It stores temperature values of temperature sensor.'''


class Temp(models.Model):
    pid = models.ForeignKey(Plants, on_delete=models.CASCADE)
    temp = models.CharField(max_length=20)
    dt = models.DateTimeField(default=datetime.now(),)

    def __str__(self):
        return str(self.temp)

'''This is a water model. It stores water level values in water tank'''


class Water(models.Model):
    uid = models.ForeignKey(User, on_delete=models.CASCADE)
    level = models.CharField(max_length=5)
    dt = models.DateTimeField(default=datetime.now(),)

    def __str__(self):
        return str(self.level)

'''This is a soil model. It stores soil moisture values of soil moisture sensor.'''


class Soil(models.Model):
    pid = models.ForeignKey(Plants, on_delete=models.CASCADE)
    m_level = models.CharField(max_length=5)
    dt = models.DateTimeField(default=datetime.now(),)

    def __str__(self):
        return str(self.m_level)

'''This is Rain model. It stores values of rain gauge.'''


class Rain(models.Model):
    uid = models.ForeignKey(User, on_delete=models.CASCADE)
    r_level = models.CharField(max_length=5)
    dt = models.DateTimeField(default=datetime.now(),)

    def __str__(self):
        return str(self.r_level)

'''This is an actuator model. It stores status of actuator whether it is on or off.'''


class Actuator(models.Model):
    pid = models.ForeignKey(Plants, on_delete=models.CASCADE)
    dt = models.DateTimeField(default=datetime.now(),)
    status = models.CharField(max_length=10)

    def __str__(self):
        return str(self.status)

Plant/views.py
from datetime import datetime
from django.shortcuts import render, HttpResponseRedirect, reverse, redirect, HttpResponse, render_to_response, get_object_or_404
from django.utils.datastructures import MultiValueDictKeyError
from .models import Plants, User, Temp, Soil, Actuator, Rain, Water


'''This function is to get data from Raspberrypi and to store in Django database.'''


def getdata(request):
    temp = request.GET['t']
    level = request.GET['cm']
    moisture = request.GET['m']
    ui = request.GET['uid']
    act = request.GET['act']
    i = request.GET['id']
    user = User.objects.filter(name=ui)[0]
    plant = Plants.objects.filter(plant_name=i, uid=user)[0]
    obj = Temp(pid = plant, temp = temp, dt = datetime.now())
    obj.save()
    obj = Water(uid = user, level = level, dt = datetime.now())
    obj.save()
    obj = Soil(pid = plant, m_level = moisture, dt = datetime.now())
    obj.save()
    obj = Actuator(pid = plant, status = act, dt = datetime.now())
    obj.save()


    return HttpResponse('this is a get request')

'''This function is to register user in the web-app'''


def signup(request):
    return render(request, 'Plant/signup-page.html', {})

'''This function is to Log user in the web-app'''


def login(request):
    return render(request, 'Plant/login-page.html', {})

'''This function is takes values from sign-in page and makes a user object in django database'''


def makeUser(request):
    try:
        alluser = User.objects.all()
        uobj = User()
        uobj.name = '_'.join(request.POST['name'].split())
        uobj.email = request.POST['email']
        for user in alluser:
            if user.email == uobj.email:
                return render(request, 'Plant/signup-page.html', {'error': 'error'})
        uobj.password = request.POST['password']
        uobj.save()
        return redirect('Plant:home', uobj.name)
    except MultiValueDictKeyError:
        return render(request, 'Plant/error-page.html', {})

'''This function is to log user in after checking whether the email-id and password is valid'''


def userprofile(request):
    try:
        st = request.POST['email']
        pt = request.POST['password']
        allusers = User.objects.all()
        for users in allusers:
            if users.email == st and users.password == pt:
                return redirect('Plant:home', users.name)
        return render(request, 'Plant/login-page.html', {'error': 'Invalid email-id or password', })
    except MultiValueDictKeyError:
        return render(request, 'Plant/error-page.html', {})

'''This function is to reload the profile page of user.'''


def home(request, name='none'):
    a = []
    if name is 'none':
        return userprofile(request)
    else:
        uobj = User.objects.get(name=name)
        plant_list = uobj.plants_set.order_by('dt')
        water_list = uobj.water_set.order_by('dt')[:10]
        rain_list = uobj.rain_set.order_by('dt')[:10]
        for plant in plant_list:
            a.append(plant.actuator_set.order_by('dt')[:1])
        return render(request, 'Plant/profile-page.html',
                      {'name': name, 'plant_list': plant_list, 'water_list': water_list, 'rain_list': rain_list, 'act_list': a})

'''This function is to log user out to the landing page.'''


def logout(request):
    return HttpResponseRedirect(reverse('Plant:login'))

'''This function is to go to respective plant page after user has selected the plant in plant list.'''


def userPlants(request, name, plant_name):
    user = User.objects.get(name=name)
    plant = Plants.objects.get(plant_name=plant_name, uid=user.id)
    temp_list = plant.temp_set.order_by('dt')[:10]
    soil_list = plant.soil_set.order_by('dt')[:10]
    return render(request, 'Plant/graph_sensor_values.html', {'temp_list': temp_list, 'soil_list': soil_list})

'''This function is to add a plant give by the user in profile page.'''


def addplant(request, name):
    uobj = User.objects.get(name=name)
    plant_name = request.POST['plant_name']
    lat = request.POST['lat']
    long = request.POST['long']
    plant = uobj.plants_set.create(plant_name=plant_name, lat=lat, lon=long)
    plant.save()
    return redirect('Plant:home', uobj.name)


'''This function is to edit the parameters of user such as username, email-id and password.'''


def editUser(request, name):
    user = User.objects.get(name=name)
    n = request.POST['name']
    if str(n) is not '':
        user.name = n
    e = request.POST['email']
    if str(e) is not '':
        user.email = e
    p = request.POST['passwd']
    if str(p) is not '':
        user.password = p
    user.save()
    return redirect('Plant:home', user.name)

Project_16/views.py
from django.shortcuts import render

'''This function is to load landing page.'''


def home(request):
    return render(request, "Plant/landing.html", {})

Plant/templates/Plant/error-page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Error</title>
</head>
<body>
    {% load staticfiles %}
    <br><br><br><br><br>
    <center><img src="{% static 'Plant/oops.jpg' %}">
    <h1>Page Not Available.</h1></center>
</body>
</html>

Plant/templates/Plant/graph_sensor_values.html
<!doctype html>
<html lang="en">
<head>
    {% load staticfiles %}
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="{% static 'Plant/signup_login/assets/img/apple-icon.png' %}">
  <link rel="icon" type="image/png" href="{% static 'Plant/signup_login/assets/img/favicon.png' %}">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

  <title>Graph</title>

  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />

  <!--     Fonts and icons     -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />

  <!-- CSS Files -->
    <link href="{% static 'Plant/signup_login/assets/css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'Plant/signup_login/assets/css/material-kit.css' %}" rel="stylesheet"/>
    <link href="{% static 'Plant/signup_login/assets/css/css3w.css' %}" rel="stylesheet"/>

</head>

<body class="landing-page">
    <nav class="navbar navbar-transparent navbar-absolute">
      <div class="container">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand">GRAPHS</a>
          </div>

      </div>
    </nav>

    <div class="wrapper">
        <div class="header header-filter" style="background-image: url('{% static 'Plant/signup_login/assets/img/examples/sensor_back.jpeg' %}'); height:300px;">

        </div>

    <div class="main main-raised w3-animate-bottom">
                <div style="height:30px"> </div>
                    <center>
                        <div id="temp_chart" style="width: 900px; height: 500px"></div>
                        <div id="SoilMoisture_chart" style="width: 900px; height: 500px"></div>
                    </center>
    </div>

    <footer class="footer">
          <div class="container" style="height: 40px;">
         </div>
      </footer>


    <div class="main main-raised" style="height: 550px; overflow:scroll;">
      <div class="container">
                <div style="height:30px"> </div>
                <div class="row">
                    <div class="col-md-6 col-md-offset-3">
                        <div class="profile-tabs">
                            <div class="nav-align-center">
                                <ul class="nav nav-pills" role="tablist">
                                    <li class="active w3-animate-left">
                                        <a href="#studio" role="tab" data-toggle="tab">
                                            <i class="material-icons">brightness_low</i>
                                            Temperature
                                        </a>
                                        <br>
                                    </li>
                                    <li class="w3-animate-right">
                                        <a href="#work" role="tab" data-toggle="tab">
                                            <i class="material-icons">select_all</i>
                                            Soil Moisture
                                        </a>
                                        <br>
                                    </li>
                                </ul>

                                <div class="tab-content gallery">
                                    <div class="tab-pane active" id="studio">
                                      {% if temp_list %}
                              {% for db in temp_list %}
                                    <p style="font-size: 20px;"><b>{{db.dt}} &emsp;&emsp;&emsp;&emsp;&emsp;&emsp; {{db.temp}}</b></p><br>
                                            {% endfor %}
                            {%else%}
                              <p> no data available </p>
                            {% endif %}
                                    </div>
                                    <div class="tab-pane text-center" id="work">
                                      {% if temp_list %}
                              {% for db in soil_list %}
                                <p style="font-size: 20px;"><b>{{db.dt}} &emsp;&emsp;&emsp;&emsp;&emsp;&emsp; {{db.m_level}}</b></p><br>
                              {% endfor %}
                            {%else%}
                              <p> no data available </p>
                            {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- End Profile Tabs -->
                    </div>
          </div>
    </div>
  </div>

      <footer class="footer">
          <div class="container">
         </div>
      </footer>

  </div>

    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript" src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
    <script type="text/javascript">
      google.charts.load('current', {'packages':['corechart']});

      var new_temp,old_temp,new_moist,old_moist,flag0=0,flag2=0,po=2,x=0,c;
      old_temp=old_moist=parseFloat(0);
      {% for q in soil_list%}
            if(x==0)
              x=x+1;
              c={{q.m_level}};
        {% endfor %}
         if(c<15) po=3;
      function fn(){
       var spreadsheetId = "1eWo3wHLBqLJoJGAFkAqKp7AnmjwC2xOoP4V9qhmHuWc",
    url = "https://spreadsheets.google.com/feeds/list/" +
          spreadsheetId +
          "/od6/public/basic?alt=json";

var cs=$.get({
  url: url,
  success: function(response) {

	var data1 = response.feed.entry;
	new_temp=parseFloat(data1[0].content.$t.replace('values: ', ''));
	new_moist=parseFloat(data1[po].content.$t.replace('values: ', ''));

  }
});
 }
      google.charts.setOnLoadCallback(drawTempChart);
      google.charts.setOnLoadCallback(drawSoilMoistureChart);

      function drawTempChart() {
        var data = google.visualization.arrayToDataTable([
          ['Timeline', 'Temperature'],
          ['17',30]
        ]);
        data.removeRow(0);

        {% for temps in temp_list %}
            data.addRow([' ',{{temps.temp}}]);
        {% endfor %}


        var options = {
          animation: {"startup": true,
                      duration: 1000,
                      easing: 'linear',},
          pointSize: 10,
          pointShape: 'circle',
          title: 'Recent Temperature',
          vAxis: {title: "Temperature"},
          hAxis: {title: "Timeline->"},
          <!--lineWidth: 4,>
          <!--curveType: 'function',>

          legend: { position: 'top' },
          colors: ['#FF671C']
        };

        var chart = new google.visualization.AreaChart(document.getElementById('temp_chart'));

        var c1=0;
        function fdraw(){
		if(c1==1 && new_temp!=old_temp){
		 data.removeRow(0);
		 data.addRow([' ',new_temp]);
		 old_temp=new_temp;
		 c1=0;
		}
		if(c1==0)chart.draw(data, options);

		fn();
		c1=1;
        }
        fdraw();


  window.setInterval(fdraw, 3000);


      }


      <!-- window.setInterval(drawTempChart, 3000);-->


      function drawSoilMoistureChart() {
        var data = google.visualization.arrayToDataTable([
          ['Timeline', 'Soil Moisture'],
          [' ',30]
        ]);
        data.removeRow(0);

        {% for q in soil_list%}
            data.addRow(['17',{{q.m_level}}]);
        {% endfor %}


        var options = {
          animation: {"startup": true,
                      duration: 1000,
                      easing: 'in',},
          pointSize: 10,
          pointShape: 'circle',
          title: 'Soil Moisture',
          vAxis: {title: "Soil Moisture"},
          hAxis: {title: "Timeline->"},
          <!--lineWidth: 4,>
          <!--curveType: 'function',>

          legend: { position: 'top' },
          colors: ['#3BFC1C']
        };

        var chart = new google.visualization.AreaChart(document.getElementById('SoilMoisture_chart'));

        var c2=0;
        function fdraw(){
		if(c2==1 && new_moist!=old_moist){
		 data.removeRow(0);
		 data.addRow([' ',new_moist]);
		 old_moist=new_moist;
		 c2=0;
		}
		if(c2==0)chart.draw(data, options);
		c2=1;
        }
        fdraw();


  window.setInterval(fdraw, 3000);

      }



    </script>






</body>

  <!--   Core JS Files   -->

  <script src="{% static 'Plant/signup_login/assets/js/bootstrap.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'Plant/signup_login/assets/js/material.min.js' %}"></script>

  <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
  <script src="{% static 'Plant/signup_login/assets/js/nouislider.min.js' %}" type="text/javascript"></script>

  <!--  Plugin for the Datepicker, full documentation here: http://www.eyecon.ro/bootstrap-datepicker/ -->
  <script src="{% static 'Plant/signup_login/assets/js/bootstrap-datepicker.js' %}" type="text/javascript"></script>

  <!-- Control Center for Material Kit: activating the ripples, parallax effects, scripts from the example pages etc -->
  <script src="{% static 'Plant/signup_login/assets/js/material-kit.js' %}" type="text/javascript"></script>

</html>

Plant/templates/Plant/login-page.html
<!doctype html>
<html lang="en">
<head>
	{% load staticfiles %}
	<meta charset="utf-8" />
	<link rel="apple-touch-icon" sizes="76x76" href="{% static 'Plant/signup_login/assets/img/apple-icon.png' %}">
	<link rel="icon" type="image/png" href="{% static 'Plant/signup_login/assets/img/favicon.png' %}">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<title>LOGIN PAGE</title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />

	<!--     Fonts and icons     -->
	<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" />
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />

	<!-- CSS Files -->
    <link href="{% static 'Plant/signup_login/assets/css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'Plant/signup_login/assets/css/material-kit.css' %}" rel="stylesheet"/>
	<link href="{% static 'Plant/signup_login/assets/css/css3w.css' %}" rel="stylesheet"/>

</head>

<body class="signup-page">

	<nav class="navbar navbar-transparent navbar-absolute">
    	<div class="container">
				<a class="navbar-brand" href="{% url 'Plant:login' %}"><i class="material-icons" style="font-size: 38px;">home</i></a></li>
        		<center><h2>PLANT MONITORING SYSTEM</h2></center>

    	</div>
    </nav>


    <div class="wrapper">
		<div class="header header-filter" style="background-image: url('{% static 'Plant/signup_login/assets/img/xz.jpeg' %}'); background-size: cover; background-position: top center;">
			<div class="container">
				<div class="row">
					<div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3">
						<div class="card card-signup w3-animate-top">
							<form class="form" method="POST" action="{% url 'Plant:home' %}">
								{% csrf_token %}
								<div class="header header-primary text-center w3-animate-left" style="background: #009688;">
									<h2>LOG IN</h2>
								</div>
								<p class="text-divider">Don't have an account ?<br> <a href="{% url 'Plant:signup' %}"> SIGN UP </a></p>

								<div class="content">

									{% if error %}
									<center><p> {{ error }} </p></center>
									{% endif %}

									<div class="input-group">
										<span class="input-group-addon">
											<i class="material-icons">email</i>
										</span>
										<input type='email' name="email" class="form-control" placeholder="Email..." required autocomplete="off">
									</div>

									<div class="input-group">
										<span class="input-group-addon">
											<i class="material-icons">lock_outline</i>
										</span>
										<input type="password" name="password" placeholder="Password..." class="form-control" required autocomplete="off">
									</div>
								</div>
								<div class="footer text-center">
									<input type="submit" name="submit" value="LOG IN" class="btn btn-simple btn-primary btn-lg"/>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>


		</div>

    </div>


</body>
	<!--   Core JS Files   -->
	<script src="{% static 'Plant/signup_login/assets/js/jquery.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'Plant/signup_login/assets/js/bootstrap.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'Plant/signup_login/assets/js/material.min.js' %}"></script>

	<!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
	<script src="{% static 'Plant/signup_login/assets/js/nouislider.min.js' %}" type="text/javascript"></script>

	<!--  Plugin for the Datepicker, full documentation here: http://www.eyecon.ro/bootstrap-datepicker/ -->
	<script src="{% static 'Plant/signup_login/assets/js/bootstrap-datepicker.js' %}" type="text/javascript"></script>

	<!-- Control Center for Material Kit: activating the ripples, parallax effects, scripts from the example pages etc -->
	<script src="{% static 'Plant/signup_login/assets/js/material-kit.js' %}" type="text/javascript"></script>

</html>

Plant/templates/Plant/map.html
<html>

<head>

    <style>
    #mapCanvas {
        width: 700px;
        height: 300px;
    }
    </style>

</head>

<body>
    <div id="mapCanvas"></div>





<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAwXuXd8dL1d5rAOftiuQ9zPKrZbRztfc0&callback=initMap"async defer></script>
<script>
function initMap() {
    var map;
    var bounds = new google.maps.LatLngBounds();
    var mapOptions = {
        mapTypeId: 'roadmap'
    };

    // Display a map on the web page
    map = new google.maps.Map(document.getElementById("mapCanvas"), mapOptions);
    map.setTilt(50);

    // Multiple markers location, latitude, and longitude
    var markers = [
        ['Plant 1', 13.557075, 80.025120],
        ['PLant 2', 13.556997, 80.025321],
    ];

    // Info window content
    var infoWindowContent = [
        ['<div class="info_content">' +
        '<h3>PLant 1</h3>' +
        '<p>Marigold Plant</p>' + '</div>'],
        ['<div class="info_content">' +
        '<h3>Plant 2</h3>' +
        '<p>Orchid Plant</p>' +
        '</div>'],
    ];

    // Add multiple markers to map
    var infoWindow = new google.maps.InfoWindow(), marker, i;

    // Place each marker on the map
    for( i = 0; i < markers.length; i++ ) {
        var position = new google.maps.LatLng(markers[i][1], markers[i][2]);
        bounds.extend(position);
        marker = new google.maps.Marker({
            position: position,
            map: map,
            title: markers[i][0]
        });

        // Add info window to marker
        google.maps.event.addListener(marker, 'click', (function(marker, i) {
            return function() {
                infoWindow.setContent(infoWindowContent[i][0]);
                infoWindow.open(map, marker);
            }
        })(marker, i));

        // Center the map to fit all markers on the screen
        map.fitBounds(bounds);
    }

    // Set zoom level
    var boundsListener = google.maps.event.addListener((map), 'bounds_changed', function(event) {
        this.setZoom(18);
        google.maps.event.removeListener(boundsListener);
    });

}
// Load initialize function
google.maps.event.addDomListener(window, 'load', initMap);
</script>
</script>

</body>
</html>

Plant/templates/Plant/signup-page.html
<!doctype html>
<html lang="en">
{% load staticfiles %}
<head>
	<meta charset="utf-8" />
	<link rel="apple-touch-icon" sizes="76x76" href="{% static 'Plant/signup_login/assets/img/apple-icon.png' %}">
	<link rel="icon" type="image/png" href="{% static 'Plant/signup_login/assets/img/favicon.png' %}">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<title>SIGN UP PAGE</title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />

	<!--     Fonts and icons     -->
	<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" />
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />

	<!-- CSS Files -->
    <link href="{% static 'Plant/signup_login/assets/css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'Plant/signup_login/assets/css/material-kit.css' %}" rel="stylesheet"/>
	<link href="{% static 'Plant/signup_login/assets/css/css3w.css' %}" rel="stylesheet"/>

</head>

<body class="signup-page">

	<nav class="navbar navbar-transparent navbar-absolute">
    	<div class="container">
				<a class="navbar-brand" href="#home">HOME</a>
        		<center><h2>PLANT MONITORING SYSTEM</h2></center>

    	</div>
    </nav>


    <div class="wrapper">
		<div class="header header-filter" style="background-image: url('{% static 'Plant/signup_login/assets/img/xx.jpg' %}'); background-size: cover; background-position: top center;">
			<div class="container">
				<div class="row">
					<div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3">
						<div class="card card-signup w3-animate-top">
							<form class="form" method="POST" action="{% url 'Plant:makeUser' %}">
								{% csrf_token %}
								<div class="header header-primary text-center w3-animate-left" style="background: #009688;">
									<h2>Sign Up</h2>
								</div>
								<p class="text-divider">Already have an account <br> <a href="{% url 'Plant:login' %}"> LOG IN </a></p>

								<div class="content">

									{% if error %}
                                    <center><p> User Already Exists.</p></center>
									{% endif %}
									<div class="input-group">
										<span class="input-group-addon">
											<i class="material-icons">face</i>
										</span>
										<input name="name" class="form-control" placeholder="Name..." required autocomplete="off"/>
									</div>

									<div class="input-group">
										<span class="input-group-addon">
											<i class="material-icons">email</i>
										</span>
										<input type='email' name="email" class="form-control" placeholder="Email..." required autocomplete="off"/>
									</div>

									<div class="input-group">
										<span class="input-group-addon">
											<i class="material-icons">lock_outline</i>
										</span>
										<input type='password' name="password" placeholder="Password..." class="form-control" required autocomplete="off"/>
									</div>
								</div>
								<div class="footer text-center">
									<input type="submit" name="submit" value="Get Started" class="btn btn-simple btn-primary btn-lg" />
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>


		</div>

    </div>


</body>
	<!--   Core JS Files   -->
	<script src="{% static 'Plant/signup_login/assets/js/jquery.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'Plant/signup_login/assets/js/bootstrap.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'Plant/signup_login/assets/js/material.min.js' %}"></script>

	<!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
	<script src=".{% static 'Plant/signup_login/assets/js/nouislider.min.js' %}" type="text/javascript"></script>

	<!--  Plugin for the Datepicker, full documentation here: http://www.eyecon.ro/bootstrap-datepicker/ -->
	<script src="{% static 'Plant/signup_login/assets/js/bootstrap-datepicker.js' %}" type="text/javascript"></script>

	<!-- Control Center for Material Kit: activating the ripples, parallax effects, scripts from the example pages etc -->
	<script src="{% static 'Plant/signup_login/assets/js/material-kit.js' %}" type="text/javascript"></script>

</html>